### ISSUE TITLE
Item that has been picked has extra NBT data after the mob has been killed.

### ISSUE THREAD

**Issue by SkippyTheLost** [frikinjay/let-me-despawn#13] opened 2023-07-03 11:15 UTC
I've noticed items that get picked up have extra NBT data, causing them to no longer stack with other items.

Specifically, the data is `{Item:{tag:{Picked:1b}}}`.

Using the following command removes the extra data on all items on the ground, and allows the items to stack again:
`/execute as @e[type=minecraft:item,nbt={Item:{tag:{Picked:1b}}}] run data remove entity @s Item.tag.Picked`

Using Fabric 1.20.1 with v1.1.0

**Comment by frikinjay** [comment] 2023-07-05 12:22
The data is removed before the entity despawns, can I get a list of the mods youre using it with and a confirmation if the tag is still there after the mob despawns?

**Comment by milkembers** [comment] 2023-07-11 00:47
hello! i'm also running into this issue. i'm using mod version 1.1.1 on Minecraft 1.20.1, Forge 47.1.0
there have been a few instances where i've noticed it happening; for example:

- i killed a vanilla spider, which dropped a piece of string. a vanilla husk picked up the string. i killed the husk and picked up the string. the string still has the Picked tag and does not stack with other string. this happens as well with rotten meat, etc.
- my tamed raccoon from Alex's Mobs regularly picks up items on the ground. once the items are retrieved from him by right-clicking, they have the Picked tag and do not stack with others.
- other mobs from Alex's Mobs that pick up items as part of their gimmick don't seem to cause this issue for some reason, namely crows and seagulls do _not_ trigger the Picked tag.

i think Alex's Mobs and Respawning Animals are the only noteworthy mods we're using that would possibly interact with this, but i really have no idea. i'll attach the full modlist of the server just in case. thank you!

![2023-07-10_21-40-19](https://github.com/frikinjay/let-me-despawn/assets/61429199/b4ad1650-2bbc-4210-9f6b-285bdf0055ef)

**Comment by RipleyHyena** [comment] 2023-09-12 00:39
I'm having this issue with just Fabric API and letmedespawn-fabric-1.20-1.1.0.jar

**Comment by Kevin-Marsh** [comment] 2023-10-03 04:28
Duplicated on Allthemods 9 forge 47.1.3 version letmedespawn-1.1.1.

**Comment by LilyRose2798** [comment] 2023-10-16 04:44
The issue is that your mixin is only called when a mob despawns, not when it is killed for any other reason (player, etc):
`@Redirect(method = "checkDespawn", at = @At(value = "INVOKE", target = "Lnet/minecraft/entity/mob/MobEntity;discard()V"))`

**Comment by frikinjay** [comment] 2023-10-30 16:29
I was away for a bit, fixed in 1.2.0

**Closed by frikinjay** 2023-10-30 16:29 UTC
